libcheat.addTask(plant, true, 'auto plant');
libcheat.addTask(harvest, true, 'auto harvest');
libcheat.addTask(makeSeeds, true, 'auto make seed');
libcheat.addTask(sellPotato, true, 'auto sell');
libcheat.addTask(seedResearch, true, 'auto research');
libcheat.addTask(seedUpgrade, true, 'auto seed upgrade');
libcheat.addTask(speedUpgrade, true, 'auto speed upgrade');
libcheat.addTask(makeBakedPotato, true, 'auto bake');
libcheat.addTask(makeFries, true, 'auto fries');
libcheat.addTask(eatFood, true, 'auto eat');
libcheat.addTask(sellFood, true, 'auto sell food');
libcheat.addTask(seedResearchMax, true, 'auto max research');
libcheat.addTask(potatoStudy, true, 'auto study');
libcheat.addTask(buyFertilizer, true, 'auto fertilizer');